import image1 from "@assets/images/image1.jpeg";
import image2 from "@assets/images/image2.jpeg";
import image3 from "@assets/images/image3.jpeg";
import image4 from "@assets/images/image4.jpeg";
import image5 from "@assets/images/image5.jpeg";
import image6 from "@assets/images/image6.jpeg";
import image7 from "@assets/images/image7.jpeg";
import image8 from "@assets/images/image8.jpeg";
import image9 from "@assets/images/image9.jpeg";
import image10 from "@assets/images/image10.jpeg";
import image11 from "@assets/images/image11.jpeg";
import image12 from "@assets/images/image12.jpeg";
import image13 from "@assets/images/image13.jpeg";
import image14 from "@assets/images/image14.jpeg";
import image15 from "@assets/images/image15.jpeg";

export const User = {
  nickName: "GOOLONGE",
};

export const Items = [
  {
    id: 1,
    title: "갈색 도트 패딩",
    price: 100,
    img: image1,
    describe: "옷에 대한 설명",
  },
  {
    id: 2,
    title: "엄준식 에디션",
    price: 200,
    img: image2,
    describe: "옷에 대한 설명",
  },
  {
    id: 3,
    title: "옷3",
    price: 300,
    img: image3,
    describe: "옷에 대한 설명",
  },
  {
    id: 4,
    title: "옷4",
    price: 400,
    img: image4,
    describe: "옷에 대한 설명",
  },
  {
    id: 5,
    title: "옷1",
    price: 500,
    img: image5,
    describe: "옷에 대한 설명",
  },
  {
    id: 6,
    title: "옷6",
    price: 600,
    img: image6,
    describe: "옷에 대한 설명",
  },
  {
    id: 7,
    title: "옷7",
    price: 700,
    img: image7,
    describe: "옷에 대한 설명",
  },
  {
    id: 8,
    title: "옷8",
    price: 800,
    img: image8,
    describe: "옷에 대한 설명",
  },
  {
    id: 9,
    title: "옷9",
    price: 900,
    img: image9,
    describe: "옷에 대한 설명",
  },
  {
    id: 10,
    title: "옷10",
    price: 1000,
    img: image10,
    describe: "옷에 대한 설명",
  },
  {
    id: 11,
    title: "옷11",
    price: 1100,
    img: image11,
    describe: "옷에 대한 설명",
  },
  {
    id: 12,
    title: "옷12",
    price: 1200,
    img: image12,
    describe: "옷에 대한 설명",
  },
  {
    id: 13,
    title: "옷13",
    price: 1300,
    img: image13,
    describe: "옷에 대한 설명",
  },
  {
    id: 14,
    title: "옷14",
    price: 1400,
    img: image14,
    describe: "옷에 대한 설명",
  },
  {
    id: 15,
    title: "옷15",
    price: 1500,
    img: image15,
    describe: "옷에 대한 설명",
  },
  {
    id: 16,
    title: "갈색 도트 패딩",
    price: 100,
    img: image1,
    describe: "옷에 대한 설명",
  },
  {
    id: 17,
    title: "엄준식 에디션",
    price: 200,
    img: image2,
    describe: "옷에 대한 설명",
  },
  {
    id: 18,
    title: "옷3",
    price: 300,
    img: image3,
    describe: "옷에 대한 설명",
  },
  {
    id: 19,
    title: "옷4",
    price: 400,
    img: image4,
    describe: "옷에 대한 설명",
  },
  {
    id: 20,
    title: "옷1",
    price: 500,
    img: image5,
    describe: "옷에 대한 설명",
  },
  {
    id: 21,
    title: "옷6",
    price: 600,
    img: image6,
    describe: "옷에 대한 설명",
  },
  {
    id: 22,
    title: "옷7",
    price: 700,
    img: image7,
    describe: "옷에 대한 설명",
  },
  {
    id: 23,
    title: "옷8",
    price: 800,
    img: image8,
    describe: "옷에 대한 설명",
  },
  {
    id: 24,
    title: "옷9",
    price: 900,
    img: image9,
    describe: "옷에 대한 설명",
  },
  {
    id: 25,
    title: "옷10",
    price: 1000,
    img: image10,
    describe: "옷에 대한 설명",
  },
  {
    id: 26,
    title: "옷11",
    price: 1100,
    img: image11,
    describe: "옷에 대한 설명",
  },
  {
    id: 27,
    title: "옷12",
    price: 1200,
    img: image12,
    describe: "옷에 대한 설명",
  },
  {
    id: 28,
    title: "옷13",
    price: 1300,
    img: image13,
    describe: "옷에 대한 설명",
  },
  {
    id: 29,
    title: "옷14",
    price: 1400,
    img: image14,
    describe: "옷에 대한 설명",
  },
  {
    id: 30,
    title: "옷15",
    price: 1500,
    img: image15,
    describe: "옷에 대한 설명",
  },
  {
    id: 31,
    title: "갈색 도트 패딩",
    price: 100,
    img: image1,
    describe: "옷에 대한 설명",
  },
  {
    id: 32,
    title: "엄준식 에디션",
    price: 200,
    img: image2,
    describe: "옷에 대한 설명",
  },
  {
    id: 33,
    title: "옷3",
    price: 300,
    img: image3,
    describe: "옷에 대한 설명",
  },
  {
    id: 34,
    title: "옷4",
    price: 400,
    img: image4,
    describe: "옷에 대한 설명",
  },
  {
    id: 35,
    title: "옷1",
    price: 500,
    img: image5,
    describe: "옷에 대한 설명",
  },
  {
    id: 36,
    title: "옷6",
    price: 600,
    img: image6,
    describe: "옷에 대한 설명",
  },
  {
    id: 37,
    title: "옷7",
    price: 700,
    img: image7,
    describe: "옷에 대한 설명",
  },
  {
    id: 38,
    title: "옷8",
    price: 800,
    img: image8,
    describe: "옷에 대한 설명",
  },
  {
    id: 39,
    title: "옷9",
    price: 900,
    img: image9,
    describe: "옷에 대한 설명",
  },
  {
    id: 40,
    title: "옷10",
    price: 1000,
    img: image10,
    describe: "옷에 대한 설명",
  },
  {
    id: 41,
    title: "옷11",
    price: 1100,
    img: image11,
    describe: "옷에 대한 설명",
  },
  {
    id: 42,
    title: "옷12",
    price: 1200,
    img: image12,
    describe: "옷에 대한 설명",
  },
  {
    id: 43,
    title: "옷13",
    price: 1300,
    img: image13,
    describe: "옷에 대한 설명",
  },
  {
    id: 44,
    title: "옷14",
    price: 1400,
    img: image14,
    describe: "옷에 대한 설명",
  },
  {
    id: 45,
    title: "옷15",
    price: 1500,
    img: image15,
    describe: "옷에 대한 설명",
  },
  {
    id: 46,
    title: "갈색 도트 패딩",
    price: 100,
    img: image1,
    describe: "옷에 대한 설명",
  },
  {
    id: 47,
    title: "엄준식 에디션",
    price: 200,
    img: image2,
    describe: "옷에 대한 설명",
  },
  {
    id: 48,
    title: "옷3",
    price: 300,
    img: image3,
    describe: "옷에 대한 설명",
  },
  {
    id: 49,
    title: "옷4",
    price: 400,
    img: image4,
    describe: "옷에 대한 설명",
  },
  {
    id: 50,
    title: "옷1",
    price: 500,
    img: image5,
    describe: "옷에 대한 설명",
  },
  {
    id: 51,
    title: "옷6",
    price: 600,
    img: image6,
    describe: "옷에 대한 설명",
  },
  {
    id: 52,
    title: "옷7",
    price: 700,
    img: image7,
    describe: "옷에 대한 설명",
  },
  {
    id: 53,
    title: "옷8",
    price: 800,
    img: image8,
    describe: "옷에 대한 설명",
  },
  {
    id: 54,
    title: "옷9",
    price: 900,
    img: image9,
    describe: "옷에 대한 설명",
  },
  {
    id: 55,
    title: "옷10",
    price: 1000,
    img: image10,
    describe: "옷에 대한 설명",
  },
  {
    id: 56,
    title: "옷11",
    price: 1100,
    img: image11,
    describe: "옷에 대한 설명",
  },
  {
    id: 57,
    title: "옷12",
    price: 1200,
    img: image12,
    describe: "옷에 대한 설명",
  },
  {
    id: 58,
    title: "옷13",
    price: 1300,
    img: image13,
    describe: "옷에 대한 설명",
  },
  {
    id: 59,
    title: "옷14",
    price: 1400,
    img: image14,
    describe: "옷에 대한 설명",
  },
  {
    id: 60,
    title: "옷15",
    price: 1500,
    img: image15,
    describe: "옷에 대한 설명",
  },
];
